model_name: kykim/electra-kor-base
normalization: False
training:
  batch_size: 32
  max_epoch: 8
  shuffle: True  
  early_stop: True
  learning_rate: 3.644751954615094e-05
  train_path': '../../data/train_preprocess_v1.csv'
  criterion: MSELoss
  optimizer:
    name: AdamW
    weight_decay: 0.0008829022519519888
  scheduler:
    name: CosineAnnealingWarmRestarts
    patience: 3
    t0: 2
    tmult: 2
    etaMin: 9.064086440201119e-05
  hpo: "" # "wandb_sweep" or "optuna"


test:
  dev_path': '../../data/dev_preprocess_v1.csv'
  test_path': '../../data/dev_preprocess_v1.csv'
  predict_path': '../../data/test_preprocess_v1.csv'