model_name: monologg/koelectra-base-v3-discriminator
normalization : False
training:
  batch_size: 16
  max_epoch: 10
  shuffle: True
  early_stop: True
  learning_rate: 0.00001
  train_path': '../data/train_preprocess_v1.csv'
  criterion: L1Loss
  optimizer:
    name: AdamW
    weight_decay: 0.001
  scheduler:
    name: CosineAnnealingWarmRestarts
    patience: 2
    etaMin: 0.00001
    t0: 2
    tmult: 2
  hpo: ""
test:
  dev_path': '../data/dev_preprocess_v1.csv'
  test_path': '../data/dev_preprocess_v1.csv'
  predict_path': '../data/test_preprocess_v1.csv'