model_name: klue/roberta-base
normalization: False
training:
  batch_size: 16
  max_epoch: 10
  shuffle: True  
  early_stop: False
  learning_rate: 0.00003
  train_path': '/data/ephemeral/home/ljin/test/train_preprocess_v1.csv'
  criterion: MSELoss
  optimizer:
    name: AdamW
    weight_decay: 0.01
  scheduler:
    name: CosineAnnealingWarmRestarts
    patience: 3
    t0: 5
    tmult: 2
    etaMin: 0.00001
  hpo: "" # "wandb_sweep" or "optuna"


test:
  dev_path': '/data/ephemeral/home/ljin/test/dev_preprocess_v1.csv'
  test_path': '/data/ephemeral/home/ljin/test/dev_preprocess_v1.csv'
  predict_path': '/data/ephemeral/home/ljin/test/test_preprocess_v1.csv'