model_name: klue/roberta-small
training:
  batch_size: 32
  max_epoch: 1
  shuffle: True
  learning_rate: 0.00002
  train_path': '../data/train.csv'
  loss: MSELoss
  optimization:
    name: AdamW
    weight_decay: 0.01
  scheduler:
    name: ReduceLROnPlateau
    patience: 5
test:
  dev_path: '../data/dev.csv'
  test_path: '../data/dev.csv'
  predict_path: '../data/test.csv'