model_name: klue/roberta-small
normalization: True
training:
  batch_size: 32
  max_epoch: 1
  shuffle: True  
  early_stop: True
  learning_rate: 0.00002
  train_path': '../../data/train.csv'
  criterion: MSELoss
  optimizer:
    name: AdamW
    weight_decay: 0.01
  scheduler:
    name: CosineAnnealingWarmRestarts
    patience: 3
    t0: 5
    tmult: 2
    etaMin: 0.00001
  hpo: ""


test:
  dev_path': '../../data/dev.csv'
  test_path': '../../data/dev.csv'
  predict_path': '../../data/test.csv'