model_name: deliciouscat/kf-deberta-base-cross-sts
normalization: True
training:
  batch_size: 16
  max_epoch: 3
  shuffle: True
  early_stop: True
  learning_rate: 0.00001
  train_path': '../../data/train.csv'
  loss: MSELoss
  optimization:
    name: AdamW
    weight_decay: 0.01
  scheduler:
    name: CosineAnnealingWarmRestarts
    t0: 5
    tmult: 2
    etaMin: 0.00001
test:
  dev_path': '../../data/dev.csv'
  test_path': '../../data/dev.csv'
  predict_path': '../../data/test.csv'